import type { TokenKey } from "./token-keys";

export const tokenToCssVar: Record<TokenKey, `--kz-${string}`> = {
  "color.brand.primary": "--kz-color-brand-primary",
  "color.brand.primary.hover": "--kz-color-brand-primary-hover",
  "color.brand.primary.active": "--kz-color-brand-primary-active",
  "color.brand.secondary": "--kz-color-brand-secondary",
  "color.brand.accent": "--kz-color-brand-accent",
  "color.brand.accent.hover": "--kz-color-brand-accent-hover",
  "color.brand.accent.active": "--kz-color-brand-accent-active",
  "color.brand.inverse": "--kz-color-brand-inverse",

  "color.surface.background": "--kz-color-surface-background",
  "color.surface.base": "--kz-color-surface-base",
  "color.surface.raised": "--kz-color-surface-raised",
  "color.surface.sunken": "--kz-color-surface-sunken",
  "color.surface.overlay": "--kz-color-surface-overlay",
  "color.surface.glass": "--kz-color-surface-glass",
  "color.surface.muted": "--kz-color-surface-muted",
  "color.surface.inverse": "--kz-color-surface-inverse",

  "color.text.primary": "--kz-color-text-primary",
  "color.text.secondary": "--kz-color-text-secondary",
  "color.text.tertiary": "--kz-color-text-tertiary",
  "color.text.muted": "--kz-color-text-muted",
  "color.text.disabled": "--kz-color-text-disabled",
  "color.text.inverse": "--kz-color-text-inverse",
  "color.text.link": "--kz-color-text-link",
  "color.text.link.hover": "--kz-color-text-link-hover",

  "color.border.subtle": "--kz-color-border-subtle",
  "color.border.default": "--kz-color-border-default",
  "color.border.strong": "--kz-color-border-strong",
  "color.border.focus": "--kz-color-border-focus",
  "color.border.inverse": "--kz-color-border-inverse",

  "color.status.success": "--kz-color-status-success",
  "color.status.success.bg": "--kz-color-status-success-bg",
  "color.status.success.border": "--kz-color-status-success-border",
  "color.status.warning": "--kz-color-status-warning",
  "color.status.warning.bg": "--kz-color-status-warning-bg",
  "color.status.warning.border": "--kz-color-status-warning-border",
  "color.status.error": "--kz-color-status-error",
  "color.status.error.bg": "--kz-color-status-error-bg",
  "color.status.error.border": "--kz-color-status-error-border",
  "color.status.info": "--kz-color-status-info",
  "color.status.info.bg": "--kz-color-status-info-bg",
  "color.status.info.border": "--kz-color-status-info-border",

  "shadow.elevation.0": "--kz-shadow-elevation-0",
  "shadow.elevation.1": "--kz-shadow-elevation-1",
  "shadow.elevation.2": "--kz-shadow-elevation-2",
  "shadow.elevation.3": "--kz-shadow-elevation-3",
  "shadow.elevation.4": "--kz-shadow-elevation-4",
  "shadow.elevation.5": "--kz-shadow-elevation-5",
  "shadow.inset.1": "--kz-shadow-inset-1",
  "shadow.inset.2": "--kz-shadow-inset-2",
  "shadow.focus": "--kz-shadow-focus",
  "shadow.neumorphic.light": "--kz-shadow-neumorphic-light",
  "shadow.neumorphic.dark": "--kz-shadow-neumorphic-dark",

  "effect.blur.sm": "--kz-effect-blur-sm",
  "effect.blur.md": "--kz-effect-blur-md",
  "effect.blur.lg": "--kz-effect-blur-lg",
  "effect.glass.opacity": "--kz-effect-glass-opacity",
  "effect.glass.border.opacity": "--kz-effect-glass-border-opacity",

  "radius.none": "--kz-radius-none",
  "radius.xs": "--kz-radius-xs",
  "radius.sm": "--kz-radius-sm",
  "radius.md": "--kz-radius-md",
  "radius.lg": "--kz-radius-lg",
  "radius.xl": "--kz-radius-xl",
  "radius.full": "--kz-radius-full",

  "space.0": "--kz-space-0",
  "space.1": "--kz-space-1",
  "space.2": "--kz-space-2",
  "space.3": "--kz-space-3",
  "space.4": "--kz-space-4",
  "space.5": "--kz-space-5",
  "space.6": "--kz-space-6",
  "space.8": "--kz-space-8",
  "space.10": "--kz-space-10",
  "space.12": "--kz-space-12",
  "space.16": "--kz-space-16",
  "space.20": "--kz-space-20",
  "space.24": "--kz-space-24",

  "font.family.base": "--kz-font-family-base",
  "font.family.mono": "--kz-font-family-mono",
  "font.size.xs": "--kz-font-size-xs",
  "font.size.sm": "--kz-font-size-sm",
  "font.size.md": "--kz-font-size-md",
  "font.size.lg": "--kz-font-size-lg",
  "font.size.xl": "--kz-font-size-xl",
  "font.size.2xl": "--kz-font-size-2xl",
  "font.size.3xl": "--kz-font-size-3xl",
  "font.weight.regular": "--kz-font-weight-regular",
  "font.weight.medium": "--kz-font-weight-medium",
  "font.weight.semibold": "--kz-font-weight-semibold",
  "font.weight.bold": "--kz-font-weight-bold",
  "line.height.sm": "--kz-line-height-sm",
  "line.height.md": "--kz-line-height-md",
  "line.height.lg": "--kz-line-height-lg",

  "motion.duration.fast": "--kz-motion-duration-fast",
  "motion.duration.normal": "--kz-motion-duration-normal",
  "motion.duration.slow": "--kz-motion-duration-slow",
  "motion.easing.standard": "--kz-motion-easing-standard",
  "motion.easing.emphasized": "--kz-motion-easing-emphasized",

  "component.sidebar.bg": "--kz-component-sidebar-bg",
  "component.sidebar.border": "--kz-component-sidebar-border",
  "component.sidebar.item.bg": "--kz-component-sidebar-item-bg",
  "component.sidebar.item.bg.hover": "--kz-component-sidebar-item-bg-hover",
  "component.sidebar.item.bg.active": "--kz-component-sidebar-item-bg-active",
  "component.sidebar.item.text": "--kz-component-sidebar-item-text",
  "component.sidebar.item.text.active": "--kz-component-sidebar-item-text-active",
  "component.sidebar.indicator": "--kz-component-sidebar-indicator",

  "component.header.bg": "--kz-component-header-bg",
  "component.header.border": "--kz-component-header-border",
  "component.header.text": "--kz-component-header-text",

  "component.button.primary.bg": "--kz-component-button-primary-bg",
  "component.button.primary.bg.hover": "--kz-component-button-primary-bg-hover",
  "component.button.primary.bg.active": "--kz-component-button-primary-bg-active",
  "component.button.primary.text": "--kz-component-button-primary-text",
  "component.button.primary.shadow": "--kz-component-button-primary-shadow",
  "component.button.secondary.bg": "--kz-component-button-secondary-bg",
  "component.button.secondary.text": "--kz-component-button-secondary-text",
  "component.button.secondary.border": "--kz-component-button-secondary-border",
  "component.button.danger.bg": "--kz-component-button-danger-bg",
  "component.button.danger.text": "--kz-component-button-danger-text",

  "component.input.bg": "--kz-component-input-bg",
  "component.input.border": "--kz-component-input-border",
  "component.input.border.focus": "--kz-component-input-border-focus",
  "component.input.text": "--kz-component-input-text",
  "component.input.placeholder": "--kz-component-input-placeholder",
  "component.input.shadow": "--kz-component-input-shadow",
  "component.input.radius": "--kz-component-input-radius",

  "component.card.bg": "--kz-component-card-bg",
  "component.card.border": "--kz-component-card-border",
  "component.card.shadow": "--kz-component-card-shadow",
  "component.card.radius": "--kz-component-card-radius",

  "component.canvas.bg": "--kz-component-canvas-bg",
  "component.canvas.grid.line": "--kz-component-canvas-grid-line",
  "component.tile.bg": "--kz-component-tile-bg",
  "component.tile.border": "--kz-component-tile-border",
  "component.tile.shadow": "--kz-component-tile-shadow",
  "component.tile.header.bg": "--kz-component-tile-header-bg",
  "component.tile.header.text": "--kz-component-tile-header-text",

  "component.filter.panel.bg": "--kz-component-filter-panel-bg",
  "component.filter.panel.border": "--kz-component-filter-panel-border",
  "component.filter.label.text": "--kz-component-filter-label-text",
  "component.filter.control.bg": "--kz-component-filter-control-bg",
  "component.filter.control.border": "--kz-component-filter-control-border",
};
