import type { TokenKey } from "./token-keys";

export const tokenToCssVar: Record<TokenKey, `--kz-${string}`> = {
  "color.brand.primary": "--kz-color-brand-primary",
  "color.brand.primary.hover": "--kz-color-brand-primary-hover",
  "color.brand.primary.active": "--kz-color-brand-primary-active",
  "color.brand.secondary": "--kz-color-brand-secondary",
  "color.brand.accent": "--kz-color-brand-accent",
  "color.brand.accent.hover": "--kz-color-brand-accent-hover",
  "color.brand.accent.active": "--kz-color-brand-accent-active",
  "color.brand.inverse": "--kz-color-brand-inverse",

  "color.surface.background": "--kz-color-surface-background",
  "color.surface.base": "--kz-color-surface-base",
  "color.surface.raised": "--kz-color-surface-raised",
  "color.surface.sunken": "--kz-color-surface-sunken",
  "color.surface.overlay": "--kz-color-surface-overlay",
  "color.surface.glass": "--kz-color-surface-glass",
  "color.surface.muted": "--kz-color-surface-muted",
  "color.surface.inverse": "--kz-color-surface-inverse",

  "color.text.primary": "--kz-color-text-primary",
  "color.text.secondary": "--kz-color-text-secondary",
  "color.text.tertiary": "--kz-color-text-tertiary",
  "color.text.muted": "--kz-color-text-muted",
  "color.text.disabled": "--kz-color-text-disabled",
  "color.text.inverse": "--kz-color-text-inverse",
  "color.text.link": "--kz-color-text-link",
  "color.text.link.hover": "--kz-color-text-link-hover",

  "color.border.subtle": "--kz-color-border-subtle",
  "color.border.default": "--kz-color-border-default",
  "color.border.strong": "--kz-color-border-strong",
  "color.border.focus": "--kz-color-border-focus",
  "color.border.inverse": "--kz-color-border-inverse",

  "color.status.success": "--kz-color-status-success",
  "color.status.success.bg": "--kz-color-status-success-bg",
  "color.status.success.border": "--kz-color-status-success-border",
  "color.status.warning": "--kz-color-status-warning",
  "color.status.warning.bg": "--kz-color-status-warning-bg",
  "color.status.warning.border": "--kz-color-status-warning-border",
  "color.status.error": "--kz-color-status-error",
  "color.status.error.bg": "--kz-color-status-error-bg",
  "color.status.error.border": "--kz-color-status-error-border",
  "color.status.info": "--kz-color-status-info",
  "color.status.info.bg": "--kz-color-status-info-bg",
  "color.status.info.border": "--kz-color-status-info-border",

  "shadow.elevation.0": "--kz-shadow-elevation-0",
  "shadow.elevation.1": "--kz-shadow-elevation-1",
  "shadow.elevation.2": "--kz-shadow-elevation-2",
  "shadow.elevation.3": "--kz-shadow-elevation-3",
  "shadow.elevation.4": "--kz-shadow-elevation-4",
  "shadow.elevation.5": "--kz-shadow-elevation-5",
  "shadow.inset.1": "--kz-shadow-inset-1",
  "shadow.inset.2": "--kz-shadow-inset-2",
  "shadow.focus": "--kz-shadow-focus",
  "shadow.neumorphic.light": "--kz-shadow-neumorphic-light",
  "shadow.neumorphic.dark": "--kz-shadow-neumorphic-dark",

  "effect.blur.sm": "--kz-effect-blur-sm",
  "effect.blur.md": "--kz-effect-blur-md",
  "effect.blur.lg": "--kz-effect-blur-lg",
  "effect.glass.opacity": "--kz-effect-glass-opacity",
  "effect.glass.border.opacity": "--kz-effect-glass-border-opacity",

  "radius.none": "--kz-radius-none",
  "radius.xs": "--kz-radius-xs",
  "radius.sm": "--kz-radius-sm",
  "radius.md": "--kz-radius-md",
  "radius.lg": "--kz-radius-lg",
  "radius.xl": "--kz-radius-xl",
  "radius.full": "--kz-radius-full",

  "space.0": "--kz-space-0",
  "space.1": "--kz-space-1",
  "space.2": "--kz-space-2",
  "space.3": "--kz-space-3",
  "space.4": "--kz-space-4",
  "space.5": "--kz-space-5",
  "space.6": "--kz-space-6",
  "space.8": "--kz-space-8",
  "space.10": "--kz-space-10",
  "space.12": "--kz-space-12",
  "space.16": "--kz-space-16",
  "space.20": "--kz-space-20",
  "space.24": "--kz-space-24",

  "font.family.base": "--kz-font-family-base",
  "font.family.mono": "--kz-font-family-mono",
  "font.size.xs": "--kz-font-size-xs",
  "font.size.sm": "--kz-font-size-sm",
  "font.size.md": "--kz-font-size-md",
  "font.size.lg": "--kz-font-size-lg",
  "font.size.xl": "--kz-font-size-xl",
  "font.size.2xl": "--kz-font-size-2xl",
  "font.size.3xl": "--kz-font-size-3xl",
  "font.weight.regular": "--kz-font-weight-regular",
  "font.weight.medium": "--kz-font-weight-medium",
  "font.weight.semibold": "--kz-font-weight-semibold",
  "font.weight.bold": "--kz-font-weight-bold",
  "line.height.sm": "--kz-line-height-sm",
  "line.height.md": "--kz-line-height-md",
  "line.height.lg": "--kz-line-height-lg",

  "motion.duration.fast": "--kz-motion-duration-fast",
  "motion.duration.normal": "--kz-motion-duration-normal",
  "motion.duration.slow": "--kz-motion-duration-slow",
  "motion.easing.standard": "--kz-motion-easing-standard",
  "motion.easing.emphasized": "--kz-motion-easing-emphasized",

  "component.sidebar.bg": "--kz-component-sidebar-bg",
  "component.sidebar.border": "--kz-component-sidebar-border",
  "component.sidebar.item.bg": "--kz-component-sidebar-item-bg",
  "component.sidebar.item.bg.hover": "--kz-component-sidebar-item-bg-hover",
  "component.sidebar.item.bg.active": "--kz-component-sidebar-item-bg-active",
  "component.sidebar.item.text": "--kz-component-sidebar-item-text",
  "component.sidebar.item.text.active":
    "--kz-component-sidebar-item-text-active",
  "component.sidebar.indicator": "--kz-component-sidebar-indicator",

  "component.header.bg": "--kz-component-header-bg",
  "component.header.border": "--kz-component-header-border",
  "component.header.text": "--kz-component-header-text",

  "component.button.primary.bg": "--kz-component-button-primary-bg",
  "component.button.primary.bg.hover": "--kz-component-button-primary-bg-hover",
  "component.button.primary.bg.active":
    "--kz-component-button-primary-bg-active",
  "component.button.primary.text": "--kz-component-button-primary-text",
  "component.button.primary.shadow": "--kz-component-button-primary-shadow",
  "component.button.primary.shadow.hover":
    "--kz-component-button-primary-shadow-hover",
  "component.button.secondary.bg": "--kz-component-button-secondary-bg",
  "component.button.secondary.bg.hover":
    "--kz-component-button-secondary-bg-hover",
  "component.button.secondary.bg.active":
    "--kz-component-button-secondary-bg-active",
  "component.button.secondary.text": "--kz-component-button-secondary-text",
  "component.button.secondary.shadow": "--kz-component-button-secondary-shadow",
  "component.button.secondary.shadow.hover":
    "--kz-component-button-secondary-shadow-hover",
  "component.button.outline.bg": "--kz-component-button-outline-bg",
  "component.button.outline.bg.hover": "--kz-component-button-outline-bg-hover",
  "component.button.outline.border": "--kz-component-button-outline-border",
  "component.button.outline.text": "--kz-component-button-outline-text",
  "component.button.outline.shadow": "--kz-component-button-outline-shadow",
  "component.button.outline.shadow.hover":
    "--kz-component-button-outline-shadow-hover",
  "component.button.ghost.bg": "--kz-component-button-ghost-bg",
  "component.button.ghost.bg.hover": "--kz-component-button-ghost-bg-hover",
  "component.button.ghost.text": "--kz-component-button-ghost-text",
  "component.button.success.bg": "--kz-component-button-success-bg",
  "component.button.success.bg.hover": "--kz-component-button-success-bg-hover",
  "component.button.success.text": "--kz-component-button-success-text",
  "component.button.success.shadow": "--kz-component-button-success-shadow",
  "component.button.success.shadow.hover":
    "--kz-component-button-success-shadow-hover",
  "component.button.warning.bg": "--kz-component-button-warning-bg",
  "component.button.warning.bg.hover": "--kz-component-button-warning-bg-hover",
  "component.button.warning.text": "--kz-component-button-warning-text",
  "component.button.warning.shadow": "--kz-component-button-warning-shadow",
  "component.button.warning.shadow.hover":
    "--kz-component-button-warning-shadow-hover",
  "component.button.error.bg": "--kz-component-button-error-bg",
  "component.button.error.bg.hover": "--kz-component-button-error-bg-hover",
  "component.button.error.text": "--kz-component-button-error-text",
  "component.button.error.shadow": "--kz-component-button-error-shadow",
  "component.button.error.shadow.hover":
    "--kz-component-button-error-shadow-hover",
  "component.button.radius": "--kz-component-button-radius",
  "component.button.disabled.opacity": "--kz-component-button-disabled-opacity",
  "component.button.loading.opacity": "--kz-component-button-loading-opacity",

  "component.input.bg": "--kz-component-input-bg",
  "component.input.border": "--kz-component-input-border",
  "component.input.border.focus": "--kz-component-input-border-focus",
  "component.input.border.disabled": "--kz-component-input-border-disabled",
  "component.input.text": "--kz-component-input-text",
  "component.input.placeholder": "--kz-component-input-placeholder",
  "component.input.icon": "--kz-component-input-icon",
  "component.input.shadow": "--kz-component-input-shadow",
  "component.input.radius": "--kz-component-input-radius",
  "component.input.container.radius": "--kz-component-input-container-radius",
  "component.input.container.border": "--kz-component-input-container-border",

  "component.dropdown.trigger.bg": "--kz-component-dropdown-trigger-bg",
  "component.dropdown.trigger.border": "--kz-component-dropdown-trigger-border",
  "component.dropdown.trigger.border.open":
    "--kz-component-dropdown-trigger-border-open",
  "component.dropdown.trigger.text": "--kz-component-dropdown-trigger-text",
  "component.dropdown.trigger.text.selected":
    "--kz-component-dropdown-trigger-text-selected",
  "component.dropdown.trigger.shadow": "--kz-component-dropdown-trigger-shadow",
  "component.dropdown.trigger.shadow.open":
    "--kz-component-dropdown-trigger-shadow-open",
  "component.dropdown.trigger.radius": "--kz-component-dropdown-trigger-radius",
  "component.dropdown.trigger.focus.ring":
    "--kz-component-dropdown-trigger-focus-ring",
  "component.dropdown.content.bg": "--kz-component-dropdown-content-bg",
  "component.dropdown.content.border": "--kz-component-dropdown-content-border",
  "component.dropdown.content.shadow": "--kz-component-dropdown-content-shadow",
  "component.dropdown.content.radius": "--kz-component-dropdown-content-radius",
  "component.dropdown.item.text": "--kz-component-dropdown-item-text",
  "component.dropdown.item.text.selected":
    "--kz-component-dropdown-item-text-selected",
  "component.dropdown.item.bg.hover": "--kz-component-dropdown-item-bg-hover",

  "component.nav-button.icon": "--kz-component-nav-button-icon",
  "component.nav-button.text": "--kz-component-nav-button-text",
  "component.nav-button.gap": "--kz-component-nav-button-gap",
  "component.nav-button.chevron": "--kz-component-nav-button-chevron",
  "component.nav-button.hover.bg": "--kz-component-nav-button-hover-bg",
  "component.nav-button.selected.bg": "--kz-component-nav-button-selected-bg",
  "component.nav-button.selected.shadow":
    "--kz-component-nav-button-selected-shadow",
  "component.nav-button.selected.icon":
    "--kz-component-nav-button-selected-icon",
  "component.nav-button.selected.text":
    "--kz-component-nav-button-selected-text",
  "component.nav-button.radius": "--kz-component-nav-button-radius",

  "component.nav-dropdown.menu.bg": "--kz-component-nav-dropdown-menu-bg",
  "component.nav-dropdown.menu.shadow":
    "--kz-component-nav-dropdown-menu-shadow",
  "component.nav-dropdown.menu.radius":
    "--kz-component-nav-dropdown-menu-radius",
  "component.nav-dropdown.option.text":
    "--kz-component-nav-dropdown-option-text",
  "component.nav-dropdown.option.hover.bg":
    "--kz-component-nav-dropdown-option-hover-bg",

  "component.sidesheet.bg": "--kz-component-sidesheet-bg",
  "component.sidesheet.width": "--kz-component-sidesheet-width",
  "component.sidesheet.border": "--kz-component-sidesheet-border",

  "component.sidemenu.bg": "--kz-component-sidemenu-bg",
  "component.sidemenu.border": "--kz-component-sidemenu-border",
  "component.sidemenu.shadow": "--kz-component-sidemenu-shadow",
  "component.sidemenu.section.label.text":
    "--kz-component-sidemenu-section-label-text",
  "component.sidemenu.item.text": "--kz-component-sidemenu-item-text",
  "component.sidemenu.item.bg.hover": "--kz-component-sidemenu-item-bg-hover",
  "component.sidemenu.item.bg.active": "--kz-component-sidemenu-item-bg-active",
  "component.sidemenu.item.active.text":
    "--kz-component-sidemenu-item-active-text",
  "component.sidemenu.item.active.link.bg":
    "--kz-component-sidemenu-item-active-link-bg",
  "component.sidemenu.item.active.link.shadow":
    "--kz-component-sidemenu-item-active-link-shadow",
  "component.sidemenu.group.indent.bg":
    "--kz-component-sidemenu-group-indent-bg",
  "component.sidemenu.gap": "--kz-component-sidemenu-gap",
  "component.sidemenu.icon.gap": "--kz-component-sidemenu-icon-gap",
  "component.sidemenu.flyout.menu.bg": "--kz-component-sidemenu-flyout-menu-bg",
  "component.sidemenu.flyout.menu.shadow":
    "--kz-component-sidemenu-flyout-menu-shadow",
  "component.sidemenu.flyout.menu.radius":
    "--kz-component-sidemenu-flyout-menu-radius",
  "component.sidemenu.flyout.option.text":
    "--kz-component-sidemenu-flyout-option-text",
  "component.sidemenu.flyout.option.hover.bg":
    "--kz-component-sidemenu-flyout-option-hover-bg",

  "component.tooltip.bg": "--kz-component-tooltip-bg",
  "component.tooltip.text": "--kz-component-tooltip-text",
  "component.tooltip.border": "--kz-component-tooltip-border",
  "component.tooltip.shadow": "--kz-component-tooltip-shadow",
  "component.tooltip.radius": "--kz-component-tooltip-radius",
  "component.tooltip.padding.sm": "--kz-component-tooltip-padding-sm",
  "component.tooltip.padding.md": "--kz-component-tooltip-padding-md",
  "component.tooltip.padding.lg": "--kz-component-tooltip-padding-lg",
  "component.tooltip.maxWidth.sm": "--kz-component-tooltip-max-width-sm",
  "component.tooltip.maxWidth.md": "--kz-component-tooltip-max-width-md",
  "component.tooltip.maxWidth.lg": "--kz-component-tooltip-max-width-lg",
  "component.tooltip.inverse.bg": "--kz-component-tooltip-inverse-bg",
  "component.tooltip.inverse.text": "--kz-component-tooltip-inverse-text",
  "component.tooltip.success.bg": "--kz-component-tooltip-success-bg",
  "component.tooltip.success.text": "--kz-component-tooltip-success-text",
  "component.tooltip.warning.bg": "--kz-component-tooltip-warning-bg",
  "component.tooltip.warning.text": "--kz-component-tooltip-warning-text",
  "component.tooltip.error.bg": "--kz-component-tooltip-error-bg",
  "component.tooltip.error.text": "--kz-component-tooltip-error-text",

  "component.card.bg": "--kz-component-card-bg",
  "component.card.border": "--kz-component-card-border",
  "component.card.shadow": "--kz-component-card-shadow",
  "component.card.radius": "--kz-component-card-radius",

  "component.canvas.bg": "--kz-component-canvas-bg",
  "component.canvas.grid.line": "--kz-component-canvas-grid-line",
  "component.tile.bg": "--kz-component-tile-bg",
  "component.tile.border": "--kz-component-tile-border",
  "component.tile.shadow": "--kz-component-tile-shadow",
  "component.tile.header.bg": "--kz-component-tile-header-bg",
  "component.tile.header.text": "--kz-component-tile-header-text",

  "component.filter.panel.bg": "--kz-component-filter-panel-bg",
  "component.filter.panel.border": "--kz-component-filter-panel-border",
  "component.filter.label.text": "--kz-component-filter-label-text",
  "component.filter.control.bg": "--kz-component-filter-control-bg",
  "component.filter.control.border": "--kz-component-filter-control-border",

  "typography.error.color": "--kz-typography-error-color",
  "typography.success.color": "--kz-typography-success-color",
  "typography.warning.color": "--kz-typography-warning-color",
};
