export const TOKEN_KEYS = [
  // Brand
  "color.brand.primary",
  "color.brand.primary.hover",
  "color.brand.primary.active",
  "color.brand.secondary",
  "color.brand.accent",
  "color.brand.accent.hover",
  "color.brand.accent.active",
  "color.brand.inverse",

  // Surface
  "color.surface.background",
  "color.surface.base",
  "color.surface.raised",
  "color.surface.sunken",
  "color.surface.overlay",
  "color.surface.glass",
  "color.surface.muted",
  "color.surface.inverse",

  // Text
  "color.text.primary",
  "color.text.secondary",
  "color.text.tertiary",
  "color.text.muted",
  "color.text.disabled",
  "color.text.inverse",
  "color.text.link",
  "color.text.link.hover",

  // Border
  "color.border.subtle",
  "color.border.default",
  "color.border.strong",
  "color.border.focus",
  "color.border.inverse",

  // Status
  "color.status.success",
  "color.status.success.bg",
  "color.status.success.border",
  "color.status.warning",
  "color.status.warning.bg",
  "color.status.warning.border",
  "color.status.error",
  "color.status.error.bg",
  "color.status.error.border",
  "color.status.info",
  "color.status.info.bg",
  "color.status.info.border",

  // Shadows
  "shadow.elevation.0",
  "shadow.elevation.1",
  "shadow.elevation.2",
  "shadow.elevation.3",
  "shadow.elevation.4",
  "shadow.elevation.5",
  "shadow.inset.1",
  "shadow.inset.2",
  "shadow.focus",
  "shadow.neumorphic.light",
  "shadow.neumorphic.dark",

  // Effects
  "effect.blur.sm",
  "effect.blur.md",
  "effect.blur.lg",
  "effect.glass.opacity",
  "effect.glass.border.opacity",

  // Radius
  "radius.none",
  "radius.xs",
  "radius.sm",
  "radius.md",
  "radius.lg",
  "radius.xl",
  "radius.full",

  // Space
  "space.0",
  "space.1",
  "space.2",
  "space.3",
  "space.4",
  "space.5",
  "space.6",
  "space.8",
  "space.10",
  "space.12",
  "space.16",
  "space.20",
  "space.24",

  // Typography
  "font.family.base",
  "font.family.mono",
  "font.size.xs",
  "font.size.sm",
  "font.size.md",
  "font.size.lg",
  "font.size.xl",
  "font.size.2xl",
  "font.size.3xl",
  "font.weight.regular",
  "font.weight.medium",
  "font.weight.semibold",
  "font.weight.bold",
  "line.height.sm",
  "line.height.md",
  "line.height.lg",

  // Motion
  "motion.duration.fast",
  "motion.duration.normal",
  "motion.duration.slow",
  "motion.easing.standard",
  "motion.easing.emphasized",

  // Component — Sidebar
  "component.sidebar.bg",
  "component.sidebar.border",
  "component.sidebar.item.bg",
  "component.sidebar.item.bg.hover",
  "component.sidebar.item.bg.active",
  "component.sidebar.item.text",
  "component.sidebar.item.text.active",
  "component.sidebar.indicator",

  // Component — Header
  "component.header.bg",
  "component.header.border",
  "component.header.text",

  // Component — Button
  "component.button.primary.bg",
  "component.button.primary.bg.hover",
  "component.button.primary.bg.active",
  "component.button.primary.text",
  "component.button.primary.shadow",
  "component.button.primary.shadow.hover",
  "component.button.secondary.bg",
  "component.button.secondary.bg.hover",
  "component.button.secondary.bg.active",
  "component.button.secondary.text",
  "component.button.secondary.shadow",
  "component.button.secondary.shadow.hover",
  "component.button.outline.bg",
  "component.button.outline.bg.hover",
  "component.button.outline.border",
  "component.button.outline.text",
  "component.button.outline.shadow",
  "component.button.outline.shadow.hover",
  "component.button.ghost.bg",
  "component.button.ghost.bg.hover",
  "component.button.ghost.text",
  "component.button.success.bg",
  "component.button.success.bg.hover",
  "component.button.success.text",
  "component.button.success.shadow",
  "component.button.success.shadow.hover",
  "component.button.warning.bg",
  "component.button.warning.bg.hover",
  "component.button.warning.text",
  "component.button.warning.shadow",
  "component.button.warning.shadow.hover",
  "component.button.error.bg",
  "component.button.error.bg.hover",
  "component.button.error.text",
  "component.button.error.shadow",
  "component.button.error.shadow.hover",
  "component.button.radius",
  "component.button.disabled.opacity",
  "component.button.loading.opacity",

  // Component — Toggle button
  "component.toggle-button.default.bg",
  "component.toggle-button.default.bg.pressed",
  "component.toggle-button.default.text",
  "component.toggle-button.default.text.pressed",
  "component.toggle-button.primary.bg",
  "component.toggle-button.primary.bg.pressed",
  "component.toggle-button.primary.text",
  "component.toggle-button.primary.text.pressed",
  "component.toggle-button.container.bg",
  "component.toggle-button.container.bg.pressed",
  "component.toggle-button.container.text",
  "component.toggle-button.container.text.pressed",
  "component.toggle-button.radius",
  "component.toggle-button.disabled.opacity",
  "component.toggle-button.loading.opacity",
  "component.toggle-button.pressed.shadow",
  "component.toggle-button.track.off.bg",
  "component.toggle-button.track.on.bg",
  "component.toggle-button.thumb.bg",
  "component.toggle-button.thumb.shadow",

  // Component — Checkbox
  "component.checkbox.size.sm",
  "component.checkbox.size.md",
  "component.checkbox.size.lg",
  "component.checkbox.radius",
  "component.checkbox.off.bg",
  "component.checkbox.off.border",
  "component.checkbox.off.shadow",
  "component.checkbox.on.bg",
  "component.checkbox.on.border",
  "component.checkbox.on.shadow",
  "component.checkbox.icon.color",
  "component.checkbox.disabled.opacity",
  "component.checkbox.container.off.bg",
  "component.checkbox.container.off.border",
  "component.checkbox.container.off.shadow",
  "component.checkbox.container.on.bg",
  "component.checkbox.container.on.border",
  "component.checkbox.container.on.shadow",

  // Component — Radio
  "component.radio.size.sm",
  "component.radio.size.md",
  "component.radio.size.lg",
  "component.radio.radius",
  "component.radio.off.bg",
  "component.radio.off.border",
  "component.radio.off.shadow",
  "component.radio.on.bg",
  "component.radio.on.border",
  "component.radio.on.shadow",
  "component.radio.dot.bg",
  "component.radio.dot.shadow",
  "component.radio.disabled.opacity",

  // Component — Tabs
  "component.tabs.list.bg",
  "component.tabs.list.radius",
  "component.tabs.list.shadow",
  "component.tabs.list.pill.bg",
  "component.tabs.trigger.text",
  "component.tabs.trigger.selected.text",
  "component.tabs.trigger.selected.underline",
  "component.tabs.trigger.selected.bg",
  "component.tabs.trigger.selected.shadow",
  "component.tabs.trigger.radius",
  "component.tabs.content.padding",

  // Component — Input
  "component.input.bg",
  "component.input.border",
  "component.input.border.focus",
  "component.input.border.disabled",
  "component.input.text",
  "component.input.placeholder",
  "component.input.icon",
  "component.input.shadow",
  "component.input.radius",
  "component.input.container.radius",
  "component.input.container.border",

  // Component — Dropdown
  "component.dropdown.trigger.bg",
  "component.dropdown.trigger.border",
  "component.dropdown.trigger.border.open",
  "component.dropdown.trigger.text",
  "component.dropdown.trigger.text.selected",
  "component.dropdown.trigger.shadow",
  "component.dropdown.trigger.shadow.open",
  "component.dropdown.trigger.radius",
  "component.dropdown.trigger.focus.ring",
  "component.dropdown.content.bg",
  "component.dropdown.content.border",
  "component.dropdown.content.shadow",
  "component.dropdown.content.radius",
  "component.dropdown.item.text",
  "component.dropdown.item.text.selected",
  "component.dropdown.item.bg.hover",

  // Component — Nav button (sidesheet)
  "component.nav-button.icon",
  "component.nav-button.text",
  "component.nav-button.gap",
  "component.nav-button.chevron",
  "component.nav-button.hover.bg",
  "component.nav-button.selected.bg",
  "component.nav-button.selected.shadow",
  "component.nav-button.selected.icon",
  "component.nav-button.selected.text",
  "component.nav-button.radius",

  // Component — Nav dropdown menu
  "component.nav-dropdown.menu.bg",
  "component.nav-dropdown.menu.shadow",
  "component.nav-dropdown.menu.radius",
  "component.nav-dropdown.option.text",
  "component.nav-dropdown.option.hover.bg",

  // Component — Sidesheet
  "component.sidesheet.bg",
  "component.sidesheet.width",
  "component.sidesheet.border",

  // Component — Sidemenu
  "component.sidemenu.bg",
  "component.sidemenu.border",
  "component.sidemenu.shadow",
  "component.sidemenu.section.label.text",
  "component.sidemenu.item.text",
  "component.sidemenu.item.bg.hover",
  "component.sidemenu.item.bg.active",
  "component.sidemenu.item.active.text",
  "component.sidemenu.item.active.link.bg",
  "component.sidemenu.item.active.link.shadow",
  "component.sidemenu.group.indent.bg",
  "component.sidemenu.gap",
  "component.sidemenu.icon.gap",
  "component.sidemenu.flyout.menu.bg",
  "component.sidemenu.flyout.menu.shadow",
  "component.sidemenu.flyout.menu.radius",
  "component.sidemenu.flyout.option.text",
  "component.sidemenu.flyout.option.hover.bg",

  // Component — Tooltip
  "component.tooltip.bg",
  "component.tooltip.text",
  "component.tooltip.border",
  "component.tooltip.shadow",
  "component.tooltip.radius",
  "component.tooltip.padding.sm",
  "component.tooltip.padding.md",
  "component.tooltip.padding.lg",
  "component.tooltip.maxWidth.sm",
  "component.tooltip.maxWidth.md",
  "component.tooltip.maxWidth.lg",
  "component.tooltip.inverse.bg",
  "component.tooltip.inverse.text",
  "component.tooltip.success.bg",
  "component.tooltip.success.text",
  "component.tooltip.warning.bg",
  "component.tooltip.warning.text",
  "component.tooltip.error.bg",
  "component.tooltip.error.text",

  // Component — Card
  "component.card.bg",
  "component.card.border",
  "component.card.shadow",
  "component.card.radius",

  // Component — Canvas / Tile
  "component.canvas.bg",
  "component.canvas.grid.line",
  "component.tile.bg",
  "component.tile.border",
  "component.tile.shadow",
  "component.tile.header.bg",
  "component.tile.header.text",

  "component.table.surface",
  "component.table.header.bg",
  "component.table.header.border",
  "component.table.row.border",
  "component.table.row.hover.bg",
  "component.table.sticky.row.top",
  "component.table.footer.bg",
  "component.table.pagination.bg",
  "component.table.pagination.active.bg",
  "component.table.pagination.active.shadow",
  "component.table.pagination.hover.shadow",

  // Component — Filter panel
  "component.filter.panel.bg",
  "component.filter.panel.border",
  "component.filter.label.text",
  "component.filter.control.bg",
  "component.filter.control.border",

  // Typography status colors (overridable via KezelThemeProvider tokens)
  "typography.error.color",
  "typography.success.color",
  "typography.warning.color",
] as const;

export type TokenKey = (typeof TOKEN_KEYS)[number];
