import type { LucideIcon } from "lucide-react";
import {
  Search,
  CircleAlert,
  CheckCircle,
  TriangleAlert,
  Loader2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  BarChart2,
  Shield,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ArrowUpDown,
  EllipsisVertical,
  Sun,
  Moon,
  Settings,
  LogOut,
  User,
  FileText,
  LockOpen,
  Calendar,
  ChartArea,
  ChartBar,
  ChartBarBig,
  ChartBarDecreasing,
  ChartBarIncreasing,
  ChartBarStacked,
  ChartCandlestick,
  ChartColumn,
  ChartColumnBig,
  ChartColumnDecreasing,
  ChartColumnIncreasing,
  ChartColumnStacked,
  ChartGantt,
  ChartLine,
  ChartNetwork,
  ChartNoAxesColumn,
  ChartNoAxesColumnDecreasing,
  ChartNoAxesColumnIncreasing,
  ChartNoAxesCombined,
  ChartNoAxesGantt,
  ChartPie,
  ChartScatter,
  ChartSpline,
  FolderKanban,
  Kanban,
  SquareChartGantt,
  SquareDashedKanban,
  SquareKanban,
  TrendingDown,
  TrendingUp,
  TrendingUpDown,
  Atom,
  GitBranch,
  Clipboard,
  Palette,
  Gauge,
  Filter,
  Grid3x3,
  RadioTower,
  BadgeCheck,
  Wallet,
  DollarSign,
  Plus,
  Building2,
  X,
} from "lucide-react";

/** Use IconName.* so users discover available icons. Values match registry keys. */
export enum IconName {
  Search = "search",
  CircleAlert = "circle-alert",
  CheckCircle = "check-circle",
  TriangleAlert = "triangle-alert",
  Loader2 = "loader-2",
  ChevronDown = "chevron-down",
  ChevronLeft = "chevron-left",
  ChevronRight = "chevron-right",
  BarChart2 = "bar-chart-2",
  Shield = "shield",
  ArrowLeft = "arrow-left",
  ArrowUp = "arrow-up",
  ArrowDown = "arrow-down",
  ArrowUpDown = "arrow-up-down",
  EllipsisVertical = "ellipsis-vertical",
  Sun = "sun",
  Moon = "moon",
  LogOut = "log-out",
  Settings = "settings",
  User = "user",
  FileText = "file-text",
  LockOpen = "lock-open",
  Calendar = "calendar",
  ChartArea = "chart-area",
  ChartBar = "chart-bar",
  ChartBarBig = "chart-bar-big",
  ChartBarDecreasing = "chart-bar-decreasing",
  ChartBarIncreasing = "chart-bar-increasing",
  ChartBarStacked = "chart-bar-stacked",
  ChartCandlestick = "chart-candlestick",
  ChartColumn = "chart-column",
  ChartColumnBig = "chart-column-big",
  ChartColumnDecreasing = "chart-column-decreasing",
  ChartColumnIncreasing = "chart-column-increasing",
  ChartColumnStacked = "chart-column-stacked",
  ChartGantt = "chart-gantt",
  ChartLine = "chart-line",
  ChartNetwork = "chart-network",
  ChartNoAxesColumn = "chart-no-axes-column",
  ChartNoAxesColumnDecreasing = "chart-no-axes-column-decreasing",
  ChartNoAxesColumnIncreasing = "chart-no-axes-column-increasing",
  ChartNoAxesCombined = "chart-no-axes-combined",
  ChartNoAxesGantt = "chart-no-axes-gantt",
  ChartPie = "chart-pie",
  ChartScatter = "chart-scatter",
  ChartSpline = "chart-spline",
  FolderKanban = "folder-kanban",
  Kanban = "kanban",
  SquareChartGantt = "square-chart-gantt",
  SquareDashedKanban = "square-dashed-kanban",
  SquareKanban = "square-kanban",
  TrendingDown = "trending-down",
  TrendingUp = "trending-up",
  TrendingUpDown = "trending-up-down",
  Atom = "atom",
  GitBranch = "git-branch",
  Clipboard = "clipboard",
  Palette = "palette",
  Gauge = "gauge",
  Filter = "filter",
  Grid3x3 = "grid-3x3",
  RadioTower = "radio-tower",
  BadgeCheck = "badge-check",
  Wallet = "wallet",
  DollarSign = "dollar-sign",
  Plus = "plus",
  Building2 = "building-2",
  X = "x",
}

export const iconRegistry: Record<IconName, LucideIcon> = {
  [IconName.Search]: Search,
  [IconName.CircleAlert]: CircleAlert,
  [IconName.CheckCircle]: CheckCircle,
  [IconName.TriangleAlert]: TriangleAlert,
  [IconName.Loader2]: Loader2,
  [IconName.ChevronDown]: ChevronDown,
  [IconName.ChevronLeft]: ChevronLeft,
  [IconName.ChevronRight]: ChevronRight,
  [IconName.BarChart2]: BarChart2,
  [IconName.Shield]: Shield,
  [IconName.ArrowLeft]: ArrowLeft,
  [IconName.ArrowUp]: ArrowUp,
  [IconName.ArrowDown]: ArrowDown,
  [IconName.ArrowUpDown]: ArrowUpDown,
  [IconName.EllipsisVertical]: EllipsisVertical,
  [IconName.Sun]: Sun,
  [IconName.Moon]: Moon,
  [IconName.LogOut]: LogOut,
  [IconName.Settings]: Settings,
  [IconName.User]: User,
  [IconName.FileText]: FileText,
  [IconName.LockOpen]: LockOpen,
  [IconName.Calendar]: Calendar,
  [IconName.ChartArea]: ChartArea,
  [IconName.ChartBar]: ChartBar,
  [IconName.ChartBarBig]: ChartBarBig,
  [IconName.ChartBarDecreasing]: ChartBarDecreasing,
  [IconName.ChartBarIncreasing]: ChartBarIncreasing,
  [IconName.ChartBarStacked]: ChartBarStacked,
  [IconName.ChartCandlestick]: ChartCandlestick,
  [IconName.ChartColumn]: ChartColumn,
  [IconName.ChartColumnBig]: ChartColumnBig,
  [IconName.ChartColumnDecreasing]: ChartColumnDecreasing,
  [IconName.ChartColumnIncreasing]: ChartColumnIncreasing,
  [IconName.ChartColumnStacked]: ChartColumnStacked,
  [IconName.ChartGantt]: ChartGantt,
  [IconName.ChartLine]: ChartLine,
  [IconName.ChartNetwork]: ChartNetwork,
  [IconName.ChartNoAxesColumn]: ChartNoAxesColumn,
  [IconName.ChartNoAxesColumnDecreasing]: ChartNoAxesColumnDecreasing,
  [IconName.ChartNoAxesColumnIncreasing]: ChartNoAxesColumnIncreasing,
  [IconName.ChartNoAxesCombined]: ChartNoAxesCombined,
  [IconName.ChartNoAxesGantt]: ChartNoAxesGantt,
  [IconName.ChartPie]: ChartPie,
  [IconName.ChartScatter]: ChartScatter,
  [IconName.ChartSpline]: ChartSpline,
  [IconName.FolderKanban]: FolderKanban,
  [IconName.Kanban]: Kanban,
  [IconName.SquareChartGantt]: SquareChartGantt,
  [IconName.SquareDashedKanban]: SquareDashedKanban,
  [IconName.SquareKanban]: SquareKanban,
  [IconName.TrendingDown]: TrendingDown,
  [IconName.TrendingUp]: TrendingUp,
  [IconName.TrendingUpDown]: TrendingUpDown,
  [IconName.Atom]: Atom,
  [IconName.GitBranch]: GitBranch,
  [IconName.Clipboard]: Clipboard,
  [IconName.Palette]: Palette,
  [IconName.Gauge]: Gauge,
  [IconName.Filter]: Filter,
  [IconName.Grid3x3]: Grid3x3,
  [IconName.RadioTower]: RadioTower,
  [IconName.BadgeCheck]: BadgeCheck,
  [IconName.Wallet]: Wallet,
  [IconName.DollarSign]: DollarSign,
  [IconName.Plus]: Plus,
  [IconName.Building2]: Building2,
  [IconName.X]: X,
};
