import type { LucideIcon } from "lucide-react";
import {
  Search,
  CircleAlert,
  CheckCircle,
  TriangleAlert,
  Loader2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  BarChart2,
  Shield,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ArrowUpDown,
  EllipsisVertical,
} from "lucide-react";

/** Use IconName.* so users discover available icons. Values match registry keys. */
export enum IconName {
  Search = "search",
  CircleAlert = "circle-alert",
  CheckCircle = "check-circle",
  TriangleAlert = "triangle-alert",
  Loader2 = "loader-2",
  ChevronDown = "chevron-down",
  ChevronLeft = "chevron-left",
  ChevronRight = "chevron-right",
  BarChart2 = "bar-chart-2",
  Shield = "shield",
  ArrowLeft = "arrow-left",
  ArrowUp = "arrow-up",
  ArrowDown = "arrow-down",
  ArrowUpDown = "arrow-up-down",
  EllipsisVertical = "ellipsis-vertical",
}

export const iconRegistry: Record<IconName, LucideIcon> = {
  [IconName.Search]: Search,
  [IconName.CircleAlert]: CircleAlert,
  [IconName.CheckCircle]: CheckCircle,
  [IconName.TriangleAlert]: TriangleAlert,
  [IconName.Loader2]: Loader2,
  [IconName.ChevronDown]: ChevronDown,
  [IconName.ChevronLeft]: ChevronLeft,
  [IconName.ChevronRight]: ChevronRight,
  [IconName.BarChart2]: BarChart2,
  [IconName.Shield]: Shield,
  [IconName.ArrowLeft]: ArrowLeft,
  [IconName.ArrowUp]: ArrowUp,
  [IconName.ArrowDown]: ArrowDown,
  [IconName.ArrowUpDown]: ArrowUpDown,
  [IconName.EllipsisVertical]: EllipsisVertical,
};
