import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    button: "src/components/button/index.ts",
    "toggle-button": "src/components/toggle-button/index.ts",
    checkbox: "src/components/checkbox/index.ts",
    "radio-button": "src/components/radio-button/index.ts",
    typography: "src/components/typography/index.ts",
    "text-input": "src/components/text-input/index.ts",
    "text-area": "src/components/text-area/index.ts",
    "number-input": "src/components/number-input/index.ts",
    dropdown: "src/components/dropdown/index.ts",
    dialog: "src/components/dialog/index.ts",
    icon: "src/icon/index.ts",
    theme: "src/theme/index.ts",
    sidemenu: "src/components/sidemenu/index.ts",
    sidesheet: "src/components/sidesheet/index.ts",
    tooltip: "src/components/tooltip/index.ts",
    tabs: "src/components/tabs/index.ts",
    table: "src/components/table/index.ts",
    avatar: "src/components/avatar/index.ts",
    "date-time-picker": "src/components/date-time-picker/index.ts",
    "date-range-picker": "src/components/date-range-picker/index.ts",
    "color-picker": "src/components/color-picker/index.ts",
    "icon-picker": "src/components/icon-picker/index.ts",
    "file-uploader": "src/components/file-uploader/index.ts",
    select: "src/components/select/index.ts",
    sidepanel: "src/components/sidepanel/index.ts",
    "form-group": "src/components/form-group/index.ts",
    modal: "src/components/modal/index.ts",
    toast: "src/components/toast/index.ts",
  },
  format: ["esm", "cjs"],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  external: ["react", "react-dom"],
  esbuildOptions(options) {
    options.conditions = ["import", "module", "browser", "default"];
  },
});
